### ISSUE TITLE
win7 64bit第一次安装完成启动后出现A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ryanbaw** [frankie-zeng/ECUBus#1]
A JavaScript error occurred in the main process

Uncaught Exception:
Error: ENOENT: no such file or directory, open

**Comment by frankie-zeng** [comment]
@ryanbaw Please provide your version information and use the newest version.

**Comment by ryanbaw** [comment]
> @ryanbaw Please provide your version information and use the newest version.

version 0.1.13

**Comment by Sudozh** [comment]
我也遇见了同样的问题，ECUBUS version v0.2.19, 电脑win11.
报如下错
![image](https://user-images.githubusercontent.com/48648312/146876096-78c3a5e0-86c5-4acc-9d10-b5f039088c72.png)

**Comment by frankie-zeng** [comment]
> 我也遇见了同样的问题，ECUBUS version v0.2.19, 电脑win11. 报如下错 ![image](https://user-images.githubusercontent.com/48648312/146876096-78c3a5e0-86c5-4acc-9d10-b5f039088c72.png)

删掉掉老的版本，重新安装一下v0.2.19 版本试试？自动升级的会有这个问题！

**Comment by Sudozh** [comment]
还是不行，但是 v0.2.16 没有问题，可以安装不报错

**Comment by frankie-zeng** [comment]
Using Release v0.2.20 !!!
