### ISSUE TITLE
UDS 0x2E 服务无法使用

### ISSUE THREAD

**Issue by startqiu** [frankie-zeng/ECUBus#19]
![1](https://user-images.githubusercontent.com/40617107/157845326-e193183c-280c-4b2b-ab04-4baf6c1bb801.png)
如图所示，提示我输入不正确，但是DID就是两字节的hex值

**Comment by frankie-zeng** [comment]
是的，应该是2个字节，下个版本会修复这个问题。
临时解决办法可以通过脚本强制更改这个数据。

**Comment by startqiu** [comment]
好的，多谢
