### ISSUE TITLE
dynamic adjustment of CANFD length

### ISSUE THREAD

**Issue by zzgg86** [frankie-zeng/ECUBus#24]
It is recommended to update to dynamic adjustment of CANFD length. For example, if the length is less than 8 bytes, a canfd message of length 8 is sent. for ECUBUS.

**Comment by frankie-zeng** [comment]
You can enable the padding , and length control.

**Comment by zzgg86** [comment]
thanks for reply！
What I mean is that after turning on padding, set the bit length to 64, and send 02 10 03. If it can automatically send 8 bytes, it does not need to be filled to 64 bytes to send. Of course, this currently does not affect usage. Just a personal tip.
thank you very much!

**Comment by frankie-zeng** [comment]
Got your point, ECUBUS uses peak can-tp library directly. the transmit length decide by the dll lib. 
I have a plan to support more USB-CAN devices and use the self can-tp library, then I can change the length as you said.

**Comment by zzgg86** [comment]
So, thanks, at the moment this problem does not affect the use. thanks again！
