### ISSUE TITLE
CAN ID display error in PEAK TP Setting

### ISSUE THREAD

**Issue by dylan-luo** [frankie-zeng/ECUBus#4]
when I configure the TA as 0x55 and SA as 0x35, then click "ADD" button, it appears mistake on Send ID (0X18db5535) and Receive ID (0X18db3535). they actually will be 0x18DA5535 and 0x18DA3555 using PCAN-View monitoring, which is correct CAN ID.

![WeChat Screenshot_20200713180201](https://user-images.githubusercontent.com/53983745/87292256-1edc9d00-c533-11ea-98b8-327975deea66.png)

**Comment by frankie-zeng** [comment]
> when I configure the TA as 0x55 and SA as 0x35, then click "ADD" button, it appears mistake on Send ID (0X18db5535) and Receive ID (0X18db3535). they actually will be 0x18DA5535 and 0x18DA3555 using PCAN-View monitoring, which is correct CAN ID.
> 
> ![WeChat Screenshot_20200713180201](https://user-images.githubusercontent.com/53983745/87292256-1edc9d00-c533-11ea-98b8-327975deea66.png)

Fix in v0.1.26 version
