### ISSUE TITLE
Provided binary files

### ISSUE THREAD

**Issue by LeventCelik** [frankie-zeng/ECUBus#45]
Hello,

I would like to use this software to flash my own code; in other words, I would like to compile my own flash_api.bin and S32k144_app_CANFD.bin. I have searched the NXP forums and the documentation, but I could not find how I could do that.

Any help is appreciated!

**Comment by frankie-zeng** [comment]
You can post the issue in the NXP community. I recall that the S32k144_app_CANFD.bin file can be obtained from the unified bootloader project, whereas the flash_api.bin is somewhat more complicated.
