### ISSUE TITLE
不支持linux吗？

### ISSUE THREAD

**Issue by feixhan** [frankie-zeng/ECUBus#5]
In file included from ../src/addons/can/peak/pcantp_napi.cpp:3:0:
../src/addons/can/peak/pcantp_napi.h:5:21: fatal error: windows.h: No such file or directory

**Comment by frankie-zeng** [comment]
目前暂时不支持linux, 现在用的是peak的dll，linux的化要把peak 的.so 加上。除了can，其他都是跨平台的。

**Comment by feixhan** [comment]
现在可以方便的去除can吗？

**Comment by frankie-zeng** [comment]
the newest commit in master branch fix this issue, which can't compile can in linux.
